version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://codepipeline-eu-central-1-57824352587
      - aws cloudfront create-invalidation --distribution-id E1WLLO0QV2MSOJ --paths "/*"